#!/bin/bash

# curl -s https://api.pwnedpasswords.com/range/2ba79

echo -n Password:
read -s password
echo;
hash="$(echo -n $password | sha1sum| tr [:lower:] [:upper:])";
prefix="${hash:0:5}";


for line in $(curl -s https://api.pwnedpasswords.com/range/$prefix); do 
    hash_remote="$(echo $line | cut -d":" -f1)";
    hash_local="${hash:5:36}";
    echo "$hash_remote --> $hash_local}";
    if [ $hash_remote == $hash_local ]; then
        echo "Password breached.";
        exit 1;
    fi;
done

echo "Password not found in breached database."
exit 0
